version: "3.9"

services:
  database:
    image: postgres:14.5-alpine
    environment:
      POSTGRES_DB: looter
      POSTGRES_USER: df3a0c53672f5158
      POSTGRES_PASSWORD: 1cda84328067515ed37db88031fc1e48
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"